export const ROLES = {
	ADMIN: 'admin',
	MANAGER: 'manager',
	NURSE: 'nurse',
	CLERK: 'clerk',
	DOCTOR: 'doctor',
};

export const ROLE_PERMISSIONS = {
	DASHBOARD: Object.values(ROLES),

	USERS: [ROLES.ADMIN, ROLES.MANAGER],

	DIAGNOSIS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.NURSE, ROLES.DOCTOR],

	DIAGNOSIS_DELETE: [ROLES.ADMIN, ROLES.MANAGER],

	MEDICAL_HISTORY: [ROLES.ADMIN, ROLES.MANAGER, ROLES.DOCTOR, ROLES.NURSE],

	APPOINTMENT_TYPES_CREATE: [ROLES.ADMIN, ROLES.MANAGER],

	PHYSICIANS_CREATE: [ROLES.ADMIN, ROLES.MANAGER],

	PATIENTS_DELETE: [ROLES.ADMIN, ROLES.MANAGER],
};
